language: cpp
compiler:
  - g++
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nasm g++-4.6-multilib gcc-multilib libc6-dev-i386
install:
  - make gmp-bootstrap
  - make gtest-bootstrap
script:
  - make -B ENABLE64BIT=Yes BUILDTYPE=Release all plugin test
  - make -B ENABLE64BIT=Yes BUILDTYPE=Debug all plugin test
  - make -B ENABLE64BIT=No BUILDTYPE=Release all plugin test
  - make -B ENABLE64BIT=No BUILDTYPE=Debug all plugin test
